[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        X-Permitted-Cross-Domain-Policies = "none"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        
        
        Content-Security-Policy = '''
            script-src 'none';
            script-src-attr 'none';
            script-src-elem 'none';
        '''
